<a href="https://colab.research.google.com/github/Liping-LZ/BDAO_DSDO_2425/blob/main/Web_crawling_and_API/Web_scraping_API_inclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Web crawling example

In [1]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

In [2]:
# URL of the website to crawl
base_url = "https://books.toscrape.com/" # Define the base url

# Set to store visited URLs
visited_urls = set()

# List to store URLs to visit next
urls_to_visit = [base_url]

In [3]:
# Function to crawl a page and extract links
def crawl_page(url):
    #here we use try & except to better handle request errors
    try:
        response = requests.get(url) # Send HTTP request to the server of the target url
        response.raise_for_status()  # Raise an exception for HTTP errors

        soup = BeautifulSoup(response.content, "html.parser") # use beautifulsoup to parse the html page

        # Extract links and enqueue new URLs
        links = [] # create an empty list for links
        for link in soup.find_all("a", href=True): # since in html links are usually in <a> tags 'href' attribute, here we use .find_all("a", href=True) to get all links
            next_url = urljoin(url, link["href"])  # get the new link from the page
            links.append(next_url) # add the new link to the links list

        return links

    except requests.exceptions.RequestException as e:
        print(f"Error crawling {url}: {e}") # if there is request error, then print "error crawling"
        return []

In [4]:
# Crawl the website
while urls_to_visit: # when urls_to_visit list is not empty, continue
    current_url = urls_to_visit.pop(0)  # Dequeue the first URL

    if current_url in visited_urls:
        continue

    print(f"Crawling: {current_url}")

    new_links = crawl_page(current_url) # get all the new links by crawl the current page
    visited_urls.add(current_url) # add the current url to visited url set
    urls_to_visit.extend(new_links) # add the new links to urls_to_visit list

print("Crawling finished.") # when there are no more new links, crawling finish

Crawling: https://books.toscrape.com/
Crawling: https://books.toscrape.com/index.html
Crawling: https://books.toscrape.com/catalogue/category/books_1/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/travel_2/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/mystery_3/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/historical-fiction_4/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/sequential-art_5/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/classics_6/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/philosophy_7/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/romance_8/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/womens-fiction_9/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/fiction_10/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/childrens_11/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/religion_12/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/nonfiction_13/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/music_14/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/default_15/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/science-fiction_16/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/sports-and-games_17/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/add-a-comment_18/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/fantasy_19/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/new-adult_20/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/young-adult_21/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/science_22/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/poetry_23/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/paranormal_24/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/art_25/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/psychology_26/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/autobiography_27/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/parenting_28/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/adult-fiction_29/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/humor_30/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/horror_31/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/history_32/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/food-and-drink_33/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/christian-fiction_34/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/business_35/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/biography_36/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/thriller_37/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/contemporary_38/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/spirituality_39/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/academic_40/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/self-help_41/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/historical_42/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/christian_43/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/suspense_44/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/short-stories_45/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/novels_46/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/health_47/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/politics_48/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/cultural_49/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/erotica_50/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/crime_51/index.html
Crawling: https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
Crawling: https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html
Crawling: https://books.toscrape.com/catalogue/soumission_998/index.html
Crawling: https://books.toscrape.com/catalogue/sharp-objects_997/index.html
Crawling: https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html
Crawling: https://books.toscrape.com/catalogue/the-requiem-red_995/index.html
Crawling: https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
Crawling: https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
Crawling: https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
Crawling: https://books.toscrape.com/catalogue/the-black-maria_991/index.html
Crawling: https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
Crawling: https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html
Crawling: https://books.toscrape.com/catalogue/set-me-free_988/index.html
Crawling: https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
Crawling: https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html
Crawling: https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
Crawling: https://books.toscrape.com/catalogue/olio_984/index.html
Crawling: https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
Crawling: https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html
Crawling: https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html
Crawling: https://books.toscrape.com/catalogue/page-2.html
Crawling: https://books.toscrape.com/catalogue/category/books_1/page-2.html
Crawling: https://books.toscrape.com/catalogue/full-moon-over-noahs-ark-an-odyssey-to-mount-ararat-and-beyond_811/index.html
Crawling: https://books.toscrape.com/catalogue/see-america-a-celebration-of-our-national-parks-treasured-sites_732/index.html
Crawling: https://books.toscrape.com/catalogue/vagabonding-an-uncommon-guide-to-the-art-of-long-term-world-travel_552/index.html
Crawling: https://books.toscrape.com/catalogue/under-the-tuscan-sun_504/index.html
Crawling: https://books.toscrape.com/catalogue/a-summer-in-europe_458/index.html
Crawling: https://books.toscrape.com/catalogue/the-great-railway-bazaar_446/index.html
Crawling: https://books.toscrape.com/catalogue/a-year-in-provence-provence-1_421/index.html
Crawling: https://books.toscrape.com/catalogue/the-road-to-little-dribbling-adventures-of-an-american-in-britain-notes-from-a-small-island-2_277/index.html
Crawling: https://books.toscrape.com/catalogue/neither-here-nor-there-travels-in-europe_198/index.html
Crawling: https://books.toscrape.com/catalogue/1000-places-to-see-before-you-die_1/index.html
Crawling: https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html
Crawling: https://books.toscrape.com/catalogue/the-past-never-ends_942/index.html
Crawling: https://books.toscrape.com/catalogue/a-murder-in-time_877/index.html
Crawling: https://books.toscrape.com/catalogue/the-murder-of-roger-ackroyd-hercule-poirot-4_852/index.html
Crawling: https://books.toscrape.com/catalogue/the-last-mile-amos-decker-2_754/index.html
Crawling: https://books.toscrape.com/catalogue/that-darkness-gardiner-and-renner-1_743/index.html
Crawling: https://books.toscrape.com/catalogue/tastes-like-fear-di-marnie-rome-3_742/index.html
Crawling: https://books.toscrape.com/catalogue/a-time-of-torment-charlie-parker-14_657/index.html
Crawling: https://books.toscrape.com/catalogue/a-study-in-scarlet-sherlock-holmes-1_656/index.html
Crawling: https://books.toscrape.com/catalogue/poisonous-max-revere-novels-3_627/index.html
Crawling: https://books.toscrape.com/catalogue/murder-at-the-42nd-street-library-raymond-ambler-1_624/index.html
Crawling: https://books.toscrape.com/catalogue/most-wanted_623/index.html
Crawling: https://books.toscrape.com/catalogue/hide-away-eve-duncan-20_620/index.html
Crawling: https://books.toscrape.com/catalogue/boar-island-anna-pigeon-19_613/index.html
Crawling: https://books.toscrape.com/catalogue/the-widow_609/index.html
Crawling: https://books.toscrape.com/catalogue/playing-with-fire_602/index.html
Crawling: https://books.toscrape.com/catalogue/what-happened-on-beale-street-secrets-of-the-south-mysteries-2_506/index.html
Crawling: https://books.toscrape.com/catalogue/the-bachelor-girls-guide-to-murder-herringford-and-watts-mysteries-1_491/index.html
Crawling: https://books.toscrape.com/catalogue/delivering-the-truth-quaker-midwife-mystery-1_464/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/mystery_3/page-2.html
Crawling: https://books.toscrape.com/catalogue/forever-and-forever-the-courtship-of-henry-longfellow-and-fanny-appleton_894/index.html
Crawling: https://books.toscrape.com/catalogue/a-flight-of-arrows-the-pathfinders-2_876/index.html
Crawling: https://books.toscrape.com/catalogue/the-house-by-the-lake_846/index.html
Crawling: https://books.toscrape.com/catalogue/mrs-houdini_821/index.html
Crawling: https://books.toscrape.com/catalogue/the-marriage-of-opposites_759/index.html
Crawling: https://books.toscrape.com/catalogue/glory-over-everything-beyond-the-kitchen-house_696/index.html
Crawling: https://books.toscrape.com/catalogue/love-lies-and-spies_622/index.html
Crawling: https://books.toscrape.com/catalogue/a-paris-apartment_612/index.html
Crawling: https://books.toscrape.com/catalogue/lilac-girls_597/index.html
Crawling: https://books.toscrape.com/catalogue/the-constant-princess-the-tudor-court-1_493/index.html
Crawling: https://books.toscrape.com/catalogue/the-invention-of-wings_448/index.html
Crawling: https://books.toscrape.com/catalogue/world-without-end-the-pillars-of-the-earth-2_420/index.html
Crawling: https://books.toscrape.com/catalogue/the-passion-of-dolssa_351/index.html
Crawling: https://books.toscrape.com/catalogue/girl-with-a-pearl-earring_322/index.html
Crawling: https://books.toscrape.com/catalogue/voyager-outlander-3_299/index.html
Crawling: https://books.toscrape.com/catalogue/the-red-tent_273/index.html
Crawling: https://books.toscrape.com/catalogue/the-last-painting-of-sara-de-vos_259/index.html
Crawling: https://books.toscrape.com/catalogue/the-guernsey-literary-and-potato-peel-pie-society_253/index.html
Crawling: https://books.toscrape.com/catalogue/girl-in-the-blue-coat_160/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/historical-fiction_4/page-2.html
Crawling: https://books.toscrape.com/catalogue/tsubasa-world-chronicle-2-tsubasa-world-chronicle-2_949/index.html
Crawling: https://books.toscrape.com/catalogue/this-one-summer_947/index.html
Crawling: https://books.toscrape.com/catalogue/the-nameless-city-the-nameless-city-1_940/index.html
Crawling: https://books.toscrape.com/catalogue/saga-volume-5-saga-collected-editions-5_923/index.html
Crawling: https://books.toscrape.com/catalogue/rat-queens-vol-3-demons-rat-queens-collected-editions-11-15_921/index.html
Crawling: https://books.toscrape.com/catalogue/princess-jellyfish-2-in-1-omnibus-vol-01-princess-jellyfish-2-in-1-omnibus-1_920/index.html
Crawling: https://books.toscrape.com/catalogue/pop-gun-war-volume-1-gift_918/index.html
Crawling: https://books.toscrape.com/catalogue/patience_916/index.html
Crawling: https://books.toscrape.com/catalogue/outcast-vol-1-a-darkness-surrounds-him-outcast-1_915/index.html
Crawling: https://books.toscrape.com/catalogue/orange-the-complete-collection-1-orange-the-complete-collection-1_914/index.html
Crawling: https://books.toscrape.com/catalogue/lumberjanes-vol-2-friendship-to-the-max-lumberjanes-5-8_907/index.html
Crawling: https://books.toscrape.com/catalogue/lumberjanes-vol-1-beware-the-kitten-holy-lumberjanes-1-4_906/index.html
Crawling: https://books.toscrape.com/catalogue/lumberjanes-vol-3-a-terrible-plan-lumberjanes-9-12_905/index.html
Crawling: https://books.toscrape.com/catalogue/i-hate-fairyland-vol-1-madly-ever-after-i-hate-fairyland-compilations-1-5_899/index.html
Crawling: https://books.toscrape.com/catalogue/i-am-a-hero-omnibus-volume-1_898/index.html
Crawling: https://books.toscrape.com/catalogue/giant-days-vol-2-giant-days-5-8_895/index.html
Crawling: https://books.toscrape.com/catalogue/danganronpa-volume-1_889/index.html
Crawling: https://books.toscrape.com/catalogue/codename-baboushka-volume-1-the-conclave-of-death_887/index.html
Crawling: https://books.toscrape.com/catalogue/camp-midnight_886/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/sequential-art_5/page-2.html
Crawling: https://books.toscrape.com/catalogue/the-secret-garden_413/index.html
Crawling: https://books.toscrape.com/catalogue/the-metamorphosis_409/index.html
Crawling: https://books.toscrape.com/catalogue/the-pilgrims-progress_353/index.html
Crawling: https://books.toscrape.com/catalogue/the-hound-of-the-baskervilles-sherlock-holmes-5_348/index.html
Crawling: https://books.toscrape.com/catalogue/little-women-little-women-1_331/index.html
Crawling: https://books.toscrape.com/catalogue/gone-with-the-wind_324/index.html
Crawling: https://books.toscrape.com/catalogue/candide_316/index.html
Crawling: https://books.toscrape.com/catalogue/animal-farm_313/index.html
Crawling: https://books.toscrape.com/catalogue/wuthering-heights_307/index.html
Crawling: https://books.toscrape.com/catalogue/the-picture-of-dorian-gray_270/index.html
Crawling: https://books.toscrape.com/catalogue/the-complete-stories-and-poems-the-works-of-edgar-allan-poe-cameo-edition_238/index.html
Crawling: https://books.toscrape.com/catalogue/beowulf_126/index.html
Crawling: https://books.toscrape.com/catalogue/and-then-there-were-none_119/index.html
Crawling: https://books.toscrape.com/catalogue/the-story-of-hong-gildong_84/index.html
Crawling: https://books.toscrape.com/catalogue/the-little-prince_72/index.html
Crawling: https://books.toscrape.com/catalogue/sense-and-sensibility_49/index.html
Crawling: https://books.toscrape.com/catalogue/of-mice-and-men_37/index.html
Crawling: https://books.toscrape.com/catalogue/emma_17/index.html
Crawling: https://books.toscrape.com/catalogue/alice-in-wonderland-alices-adventures-in-wonderland-1_5/index.html
Crawling: https://books.toscrape.com/catalogue/sophies-world_966/index.html
Crawling: https://books.toscrape.com/catalogue/the-death-of-humanity-and-the-case-for-life_932/index.html
Crawling: https://books.toscrape.com/catalogue/the-stranger_861/index.html
Crawling: https://books.toscrape.com/catalogue/proofs-of-god-classical-arguments-from-tertullian-to-barth_538/index.html
Crawling: https://books.toscrape.com/catalogue/kierkegaard-a-christian-missionary-to-christians_527/index.html
Crawling: https://books.toscrape.com/catalogue/at-the-existentialist-cafe-freedom-being-and-apricot-cocktails-with-jean-paul-sartre-simone-de-beauvoir-albert-camus-martin-heidegger-edmund-husserl-karl-jaspers-maurice-merleau-ponty-and-others_459/index.html
Crawling: https://books.toscrape.com/catalogue/critique-of-pure-reason_366/index.html
Crawling: https://books.toscrape.com/catalogue/run-spot-run-the-ethics-of-keeping-pets_106/index.html
Crawling: https://books.toscrape.com/catalogue/the-nicomachean-ethics_75/index.html
Crawling: https://books.toscrape.com/catalogue/meditations_33/index.html
Crawling: https://books.toscrape.com/catalogue/beyond-good-and-evil_6/index.html
Crawling: https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html
Crawling: https://books.toscrape.com/catalogue/black-dust_976/index.html
Crawling: https://books.toscrape.com/catalogue/her-backup-boyfriend-the-sorensen-family-1_896/index.html
Crawling: https://books.toscrape.com/catalogue/first-and-first-five-boroughs-3_893/index.html
Crawling: https://books.toscrape.com/catalogue/fifty-shades-darker-fifty-shades-2_892/index.html
Crawling: https://books.toscrape.com/catalogue/the-wedding-dress_864/index.html
Crawling: https://books.toscrape.com/catalogue/suddenly-in-love-lake-haven-1_835/index.html
Crawling: https://books.toscrape.com/catalogue/something-more-than-this_834/index.html
Crawling: https://books.toscrape.com/catalogue/doing-it-over-most-likely-to-1_802/index.html
Crawling: https://books.toscrape.com/catalogue/the-wedding-pact-the-omalleys-2_767/index.html
Crawling: https://books.toscrape.com/catalogue/hold-your-breath-search-and-rescue-1_700/index.html
Crawling: https://books.toscrape.com/catalogue/dirty-dive-bar-1_615/index.html
Crawling: https://books.toscrape.com/catalogue/take-me-home-tonight-rock-star-romance-3_605/index.html
Crawling: https://books.toscrape.com/catalogue/off-the-hook-fishing-for-trouble-1_601/index.html
Crawling: https://books.toscrape.com/catalogue/a-gentlemans-position-society-of-gentlemen-3_584/index.html
Crawling: https://books.toscrape.com/catalogue/sit-stay-love_486/index.html
Crawling: https://books.toscrape.com/catalogue/a-girls-guide-to-moving-on-new-beginnings-2_359/index.html
Crawling: https://books.toscrape.com/catalogue/the-perfect-play-play-by-play-1_352/index.html
Crawling: https://books.toscrape.com/catalogue/dark-lover-black-dagger-brotherhood-1_319/index.html
Crawling: https://books.toscrape.com/catalogue/changing-the-game-play-by-play-2_317/index.html
Crawling: https://books.toscrape.com/catalogue/category/books/romance_8/page-2.html
Crawling: https://books.toscrape.com/catalogue/i-had-a-nice-time-and-other-lies-how-to-find-love-sht-like-that_814/index.html
Crawling: https://books.toscrape.com/catalogue/will-you-wont-you-want-me_644/index.html
Crawling: https://books.toscrape.com/catalogue/keep-me-posted_594/index.html
Crawling: https://books.toscrape.com/catalogue/grey-fifty-shades-4_592/index.html
Crawling: https://books.toscrape.com/catalogue/meternity_478/index.html
Crawling: https://books.toscrape.com/catalogue/some-women_341/index.html
Crawling: https://books.toscrape.com/catalogue/shopaholic-ties-the-knot-shopaholic-3_340/index.html
Crawling: https://books.toscrape.com/catalogue/can-you-keep-a-secret_315/index.html
Crawling: https://books.toscrape.com/catalogue/twenties-girl_292/index.html
Crawling: https://books.toscrape.com/catalogue/the-undomestic-goddess_286/index.html
Crawling: https://books.toscrape.com/catalogue/the-nanny-diaries-nanny-1_265/index.html
Crawling: https://books.toscrape.com/catalogue/the-devil-wears-prada-the-devil-wears-prada-1_243/index.html
Crawling: https://books.toscrape.com/catalogue/something-borrowed-darcy-rachel-1_224/index.html
Crawling: https://books.toscrape.com/catalogue/something-blue-darcy-rachel-2_223/index.html
Crawling: https://books.toscrape.com/catalogue/ive-got-your-number_173/index.html
Crawling: https://books.toscrape.com/catalogue/the-edge-of-reason-bridget-jones-2_63/index.html
Crawling: https://books.toscrape.com/catalogue/bridget-joness-diary-bridget-jones-1_10/index.html
Crawling: https://books.toscrape.com/catalogue/private-paris-private-10_958/index.html
Crawling: https://books.toscrape.com/catalogue/we-love-you-charlie-freeman_954/index.html
Crawling: https://books.toscrape.com/catalogue/thirst_946/index.html

In [5]:
import pandas as pd
links = pd.DataFrame(visited_urls, columns = ['links'])
links

                                                  links
0     https://books.toscrape.com/catalogue/why-the-r...
1     https://books.toscrape.com/catalogue/ouran-hig...
2     https://books.toscrape.com/catalogue/giant-day...
3     https://books.toscrape.com/catalogue/the-marri...
4     https://books.toscrape.com/catalogue/10-day-gr...
...                                                 ...
1190  https://books.toscrape.com/catalogue/my-mother...
1191  https://books.toscrape.com/catalogue/the-hunge...
1192  https://books.toscrape.com/catalogue/voyager-o...
1193  https://books.toscrape.com/catalogue/carrie_67...
1194  https://books.toscrape.com/catalogue/the-hobbi...

[1195 rows x 1 columns]

## Web scraping example

In [6]:
# import packages

import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup

In [7]:
url = 'https://www.scrapethissite.com/pages/simple/' # Define the url
response = requests.get(url) # Use requests to retrieve data from a given URL

In [8]:
print(response.text)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="countries">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>
                            <strong>Population:</strong> <span class="country-population">84000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>
                            <strong>Population:</strong> <span class="country-population">4975593</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>
                            <strong>Population:</strong> <span class="country-population">29121286</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>
                            <strong>Population:</strong> <span class="country-population">86754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>
                            <strong>Population:</strong> <span class="country-population">13254</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>
                            <strong>Population:</strong> <span class="country-population">2986952</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>
                            <strong>Population:</strong> <span class="country-population">2968000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>
                            <strong>Population:</strong> <span class="country-population">13068161</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">None</span><br>
                            <strong>Population:</strong> <span class="country-population">0</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>
                            <strong>Population:</strong> <span class="country-population">41343201</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>
                            <strong>Population:</strong> <span class="country-population">57881</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>
                            <strong>Population:</strong> <span class="country-population">8205000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>
                            <strong>Population:</strong> <span class="country-population">21515754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>
                            <strong>Population:</strong> <span class="country-population">71566</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>
                            <strong>Population:</strong> <span class="country-population">26711</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>
                            <strong>Population:</strong> <span class="country-population">8303512</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>
                            <strong>Population:</strong> <span class="country-population">4590000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>
                            <strong>Population:</strong> <span class="country-population">285653</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br>
                            <strong>Population:</strong> <span class="country-population">156118464</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Brussels</span><br>
                            <strong>Population:</strong> <span class="country-population">10403000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br>

In [9]:
# Parse the whole HTML page using BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')

In [10]:
country = soup.find_all('div',class_ = 'col-md-4 country')
len(country) # Check the number of items

250

In [11]:
country[0]

<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div>

In [12]:
country[0].select('h3.country-name')

[<h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>]

In [13]:
country[0].select('h3.country-name')[0].get_text(strip=True)

'Andorra'

In [14]:
country[0].select('span.country-capital')[0].get_text(strip=True)

'Andorra la Vella'

## API example - Covid-19

In [15]:
import requests

url = "https://covid-api.com/api/regions"
response = requests.get(url)
data = response.json()

In [16]:
data

{'data': [{'iso': 'CHN', 'name': 'China'},
  {'iso': 'TWN', 'name': 'Taipei and environs'},
  {'iso': 'USA', 'name': 'US'},
  {'iso': 'JPN', 'name': 'Japan'},
  {'iso': 'THA', 'name': 'Thailand'},
  {'iso': 'KOR', 'name': 'Korea, South'},
  {'iso': 'SGP', 'name': 'Singapore'},
  {'iso': 'PHL', 'name': 'Philippines'},
  {'iso': 'MYS', 'name': 'Malaysia'},
  {'iso': 'VNM', 'name': 'Vietnam'},
  {'iso': 'AUS', 'name': 'Australia'},
  {'iso': 'MEX', 'name': 'Mexico'},
  {'iso': 'BRA', 'name': 'Brazil'},
  {'iso': 'COL', 'name': 'Colombia'},
  {'iso': 'FRA', 'name': 'France'},
  {'iso': 'NPL', 'name': 'Nepal'},
  {'iso': 'CAN', 'name': 'Canada'},
  {'iso': 'KHM', 'name': 'Cambodia'},
  {'iso': 'LKA', 'name': 'Sri Lanka'},
  {'iso': 'CIV', 'name': "Cote d'Ivoire"},
  {'iso': 'DEU', 'name': 'Germany'},
  {'iso': 'FIN', 'name': 'Finland'},
  {'iso': 'ARE', 'name': 'United Arab Emirates'},
  {'iso': 'IND', 'name': 'India'},
  {'iso': 'ITA', 'name': 'Italy'},
  {'iso': 'GBR', 'name': 'United Kingdom'},
  {'iso': 'RUS', 'name': 'Russia'},
  {'iso': 'SWE', 'name': 'Sweden'},
  {'iso': 'ESP', 'name': 'Spain'},
  {'iso': 'BEL', 'name': 'Belgium'},
  {'iso': 'Others', 'name': 'Others'},
  {'iso': 'EGY', 'name': 'Egypt'},
  {'iso': 'IRN', 'name': 'Iran'},
  {'iso': 'ISR', 'name': 'Israel'},
  {'iso': 'LBN', 'name': 'Lebanon'},
  {'iso': 'IRQ', 'name': 'Iraq'},
  {'iso': 'OMN', 'name': 'Oman'},
  {'iso': 'AFG', 'name': 'Afghanistan'},
  {'iso': 'BHR', 'name': 'Bahrain'},
  {'iso': 'KWT', 'name': 'Kuwait'},
  {'iso': 'AUT', 'name': 'Austria'},
  {'iso': 'DZA', 'name': 'Algeria'},
  {'iso': 'HRV', 'name': 'Croatia'},
  {'iso': 'CHE', 'name': 'Switzerland'},
  {'iso': 'PAK', 'name': 'Pakistan'},
  {'iso': 'GEO', 'name': 'Georgia'},
  {'iso': 'GRC', 'name': 'Greece'},
  {'iso': 'MKD', 'name': 'North Macedonia'},
  {'iso': 'NOR', 'name': 'Norway'},
  {'iso': 'ROU', 'name': 'Romania'},
  {'iso': 'DNK', 'name': 'Denmark'},
  {'iso': 'EST', 'name': 'Estonia'},
  {'iso': 'NLD', 'name': 'Netherlands'},
  {'iso': 'SMR', 'name': 'San Marino'},
  {'iso': 'AZE', 'name': 'Azerbaijan'},
  {'iso': 'BLR', 'name': 'Belarus'},
  {'iso': 'ISL', 'name': 'Iceland'},
  {'iso': 'LTU', 'name': 'Lithuania'},
  {'iso': 'NZL', 'name': 'New Zealand'},
  {'iso': 'NGA', 'name': 'Nigeria'},
  {'iso': 'IRL', 'name': 'Ireland'},
  {'iso': 'LUX', 'name': 'Luxembourg'},
  {'iso': 'MCO', 'name': 'Monaco'},
  {'iso': 'QAT', 'name': 'Qatar'},
  {'iso': 'ECU', 'name': 'Ecuador'},
  {'iso': 'CZE', 'name': 'Czechia'},
  {'iso': 'ARM', 'name': 'Armenia'},
  {'iso': 'DOM', 'name': 'Dominican Republic'},
  {'iso': 'IDN', 'name': 'Indonesia'},
  {'iso': 'PRT', 'name': 'Portugal'},
  {'iso': 'AND', 'name': 'Andorra'},
  {'iso': 'LVA', 'name': 'Latvia'},
  {'iso': 'MAR', 'name': 'Morocco'},
  {'iso': 'SAU', 'name': 'Saudi Arabia'},
  {'iso': 'SEN', 'name': 'Senegal'},
  {'iso': 'ARG', 'name': 'Argentina'},
  {'iso': 'CHL', 'name': 'Chile'},
  {'iso': 'JOR', 'name': 'Jordan'},
  {'iso': 'UKR', 'name': 'Ukraine'},
  {'iso': 'BLM', 'name': 'Saint Barthelemy'},
  {'iso': 'HUN', 'name': 'Hungary'},
  {'iso': 'FRO', 'name': 'Faroe Islands'},
  {'iso': 'GIB', 'name': 'Gibraltar'},
  {'iso': 'LIE', 'name': 'Liechtenstein'},
  {'iso': 'POL', 'name': 'Poland'},
  {'iso': 'TUN', 'name': 'Tunisia'},
  {'iso': 'PSE', 'name': 'West Bank and Gaza'},
  {'iso': 'BIH', 'name': 'Bosnia and Herzegovina'},
  {'iso': 'SVN', 'name': 'Slovenia'},
  {'iso': 'ZAF', 'name': 'South Africa'},
  {'iso': 'BTN', 'name': 'Bhutan'},
  {'iso': 'CMR', 'name': 'Cameroon'},
  {'iso': 'CRI', 'name': 'Costa Rica'},
  {'iso': 'PER', 'name': 'Peru'},
  {'iso': 'SRB', 'name': 'Serbia'},
  {'iso': 'SVK', 'name': 'Slovakia'},
  {'iso': 'TGO', 'name': 'Togo'},
  {'iso': 'VAT', 'name': 'Holy See'},
  {'iso': 'GUF', 'name': 'French Guiana'},
  {'iso': 'MLT', 'name': 'Malta'},
  {'iso': 'MTQ', 'name': 'Martinique'},
  {'iso': 'BGR', 'name': 'Bulgaria'},
  {'iso': 'MDV', 'name': 'Maldives'},
  {'iso': 'BGD', 'name': 'Bangladesh'},
  {'iso': 'MDA', 'name': 'Moldova'},
  {'iso': 'PRY', 'name': 'Paraguay'},
  {'iso': 'ALB', 'name': 'Albania'},
  {'iso': 'CYP', 'name': 'Cyprus'},
  {'iso': 'BRN', 'name': 'Brunei'},
  {'iso': 'MAC', 'name': 'Macao SAR'},
  {'iso': 'MAF', 'name': 'Saint Martin'},
  {'iso': 'BFA', 'name': 'Burkina Faso'},
  {'iso': 'GGY-JEY', 'name': 'Channel Islands'},
  {'iso': 'MNG', 'name': 'Mongolia'},
  {'iso': 'PAN', 'name': 'Panama'},
  {'iso': 'cruise', 'name': 'Cruise Ship'},
  {'iso': 'TWN', 'name': 'Taiwan*'},
  {'iso': 'BOL', 'name': 'Bolivia'},
  {'iso': 'HND', 'name': 'Honduras'},
  {'iso': 'COD', 'name': 'Congo (Kinshasa)'},
  {'iso': 'JAM', 'name': 'Jamaica'},
  {'iso': 'REU', 'name': 'Reunion'},
  {'iso': 'TUR', 'name': 'Turkey'},
  {'iso': 'CUB', 'name': 'Cuba'},
  {'iso': 'GUY', 'name': 'Guyana'},
  {'iso': 'KAZ', 'name': 'Kazakhstan'},
  {'iso': 'CYM', 'name': 'Cayman Islands'},
  {'iso': 'GLP', 'name': 'Guadeloupe'},
  {'iso': 'ETH', 'name': 'Ethiopia'},
  {'iso': 'SDN', 'name': 'Sudan'},
  {'iso': 'GIN', 'name': 'Guinea'},
  {'iso': 'ATG', 'name': 'Antigua and Barbuda'},
  {'iso': 'ABW', 'name': 'Aruba'},
  {'iso': 'KEN', 'name': 'Kenya'},
  {'iso': 'URY', 'name': 'Uruguay'},
  {'iso': 'GHA', 'name': 'Ghana'},
  {'iso': 'JEY', 'name': 'Jersey'},
  {'iso': 'NAM', 'name': 'Namibia'},
  {'iso': 'SYC', 'name': 'Seychelles'},
  {'iso': 'TTO', 'name': 'Trinidad and Tobago'},
  {'iso': 'VEN', 'name': 'Venezuela'},
  {'iso': 'CUW', 'name': 'Curacao'},
  {'iso': 'SWZ', 'name': 'Eswatini'},
  {'iso': 'GAB', 'name': 'Gabon'},
  {'iso': 'GTM', 'name': 'Guatemala'},
  {'iso': 'GGY', 'name': 'Guernsey'},
  {'iso': 'MRT', 'name': 'Mauritania'},
  {'iso': 'RWA', 'name': 'Rwanda'},
  {'iso': 'LCA', 'name': 'Saint Lucia'},
  {'iso': 'VCT', 'name': 'Saint Vincent and the Grenadines'},
  {'iso': 'SUR', 'name': 'Suriname'},
  {'iso': 'RKS', 'name': 'Kosovo'},
  {'iso': 'CAF', 'name': 'Central African Republic'},
  {'iso': 'COG', 'name': 'Congo (Brazzaville)'},
  {'iso': 'GNQ', 'name': 'Equatorial Guinea'},
  {'iso': 'UZB', 'name': 'Uzbekistan'},
  {'iso': 'GUM', 'name': 'Guam'},
  {'iso': 'PRI', 'name': 'Puerto Rico'},
  {'iso': 'BEN', 'name': 'Benin'},
  {'iso': 'GRL', 'name': 'Greenland'},
  {'iso': 'LBR', 'name': 'Liberia'},
  {'iso': 'MYT', 'name': 'Mayotte'},
  {'iso': 'SOM', 'name': 'Somalia'},
  {'iso': 'TZA', 'name': 'Tanzania'},
  {'iso': 'BHS', 'name': 'Bahamas'},
  {'iso': 'BRB', 'name': 'Barbados'},
  {'iso': 'MNE', 'name': 'Montenegro'},
  {'iso': 'GMB', 'name': 'Gambia'},
  {'iso': 'KGZ', 'name': 'Kyrgyzstan'},
  {'iso': 'MUS', 'name': 'Mauritius'},
  {'iso': 'ZMB', 'name': 'Zambia'},
  {'iso': 'DJI', 'name': 'Djibouti'},
  {'iso': 'TCD', 'name': 'Chad'},
  {'iso': 'SLV', 'name': 'El Salvador'},
  {'iso': 'FJI', 'name': 'Fiji'},
  {'iso': 'NIC', 'name': 'Nicaragua'},
  {'iso': 'MDG', 'name': 'Madagascar'},
  {'iso': 'HTI', 'name': 'Haiti'},
  {'iso': 'AGO', 'name': 'Angola'},
  {'iso': 'CPV', 'name': 'Cabo Verde'},
  {'iso': 'NER', 'name': 'Niger'},
  {'iso': 'PNG', 'name': 'Papua New Guinea'},
  {'iso': 'ZWE', 'name': 'Zimbabwe'},
  {'iso': 'TLS', 'name': 'Timor-Leste'},
  {'iso': 'ERI', 'name': 'Eritrea'},
  {'iso': 'UGA', 'name': 'Uganda'},
  {'iso': 'DMA', 'name': 'Dominica'},
  {'iso': 'GRD', 'name': 'Grenada'},
  {'iso': 'MOZ', 'name': 'Mozambique'},
  {'iso': 'SYR', 'name': 'Syria'},
  {'iso': 'BLZ', 'name': 'Belize'},
  {'iso': 'LAO', 'name': 'Laos'},
  {'iso': 'LBY', 'name': 'Libya'},
  {'iso': 'NA-SHIP-DP', 'name': 'Diamond Princess'},
  {'iso': 'GNB', 'name': 'Guinea-Bissau'},
  {'iso': 'MLI', 'name': 'Mali'},
  {'iso': 'KNA', 'name': 'Saint Kitts and Nevis'},
  {'iso': 'BWA', 'name': 'Botswana'},
  {'iso': 'BDI', 'name': 'Burundi'},
  {'iso': 'SLE', 'name': 'Sierra Leone'},
  {'iso': 'MMR', 'name': 'Burma'},
  {'iso': 'MWI', 'name': 'Malawi'},
  {'iso': 'SSD', 'name': 'South Sudan'},
  {'iso': 'ESH', 'name': 'Western Sahara'},
  {'iso': 'STP', 'name': 'Sao Tome and Principe'},
  {'iso': 'NA-SHIP-MSZ', 'name': 'MS Zaandam'},
  {'iso': 'YEM', 'name': 'Yemen'},
  {'iso': 'COM', 'name': 'Comoros'},
  {'iso': 'TJK', 'name': 'Tajikistan'},
  {'iso': 'LSO', 'name': 'Lesotho'},
  {'iso': 'SLB', 'name': 'Solomon Islands'},
  {'iso': 'MHL', 'name': 'Marshall Islands'},
  {'iso': 'VUT', 'name': 'Vanuatu'},
  {'iso': 'WSM', 'name': 'Samoa'},
  {'iso': 'KIR', 'name': 'Kiribati'},
  {'iso': 'PLW', 'name': 'Palau'},
  {'iso': 'TON', 'name': 'Tonga'},
  {'iso': 'NRU', 'name': 'Nauru'},
  {'iso': 'TUV', 'name': 'Tuvalu'}]}

In [17]:
import requests

url = "https://covid-api.com/api/reports/total?iso=GBR&date=2020-03-10"
response = requests.get(url)
data = response.json()

In [18]:
data

{'data': {'date': '2020-03-10',
  'last_update': '2020-03-10 23:53:02',
  'confirmed': 382,
  'confirmed_diff': 61,
  'deaths': 6,
  'deaths_diff': 2,
  'recovered': 18,
  'recovered_diff': 0,
  'active': 358,
  'active_diff': 59,
  'fatality_rate': 0.0157}}

In [10]:
data = response.json()
data['data']['confirmed']

382

In [ ]:
data['data']

{'date': '2020-03-10',
 'last_update': '2020-03-10 23:53:02',
 'confirmed': 382,
 'confirmed_diff': 61,
 'deaths': 6,
 'deaths_diff': 2,
 'recovered': 18,
 'recovered_diff': 0,
 'active': 358,
 'active_diff': 59,
 'fatality_rate': 0.0157}

In [11]:
import pandas as pd
pd.DataFrame.from_dict([data['data']])

,date,last_update,confirmed,confirmed_diff,deaths,deaths_diff,recovered,recovered_diff,active,active_diff,fatality_rate
0,2020-03-10,2020-03-10 23:53:02,382,61,6,2,18,0,358,59,0.0157

In [12]:
import requests

url = "https://covid-api.com/api/reports/total?iso=GBR&date="
date_range = pd.date_range(start='10/03/2020', periods=30)
data = []
for date in date_range:
  date = date.strftime('%Y-%m-%d')
  response = requests.get(url+date)
  data.append(response.json()['data'])

In [13]:
data

[{'date': '2020-10-03',
  'last_update': '2020-10-04 04:23:44',
  'confirmed': 482654,
  'confirmed_diff': 12885,
  'deaths': 42407,
  'deaths_diff': 49,
  'recovered': 2396,
  'recovered_diff': 7,
  'active': 437851,
  'active_diff': 12829,
  'fatality_rate': 0.0879},
 {'date': '2020-10-04',
  'last_update': '2020-10-05 04:23:33',
  'confirmed': 505619,
  'confirmed_diff': 22965,
  'deaths': 42440,
  'deaths_diff': 33,
  'recovered': 2403,
  'recovered_diff': 7,
  'active': 460776,
  'active_diff': 22925,
  'fatality_rate': 0.0839},
 {'date': '2020-10-05',
  'last_update': '2020-10-06 04:23:33',
  'confirmed': 518222,
  'confirmed_diff': 12603,
  'deaths': 42459,
  'deaths_diff': 19,
  'recovered': 2409,
  'recovered_diff': 6,
  'active': 473354,
  'active_diff': 12578,
  'fatality_rate': 0.0819},
 {'date': '2020-10-06',
  'last_update': '2020-10-07 04:23:40',
  'confirmed': 532779,
  'confirmed_diff': 14557,
  'deaths': 42535,
  'deaths_diff': 76,
  'recovered': 2417,
  'recovered_diff': 8,
  'active': 487827,
  'active_diff': 14473,
  'fatality_rate': 0.0798},
 {'date': '2020-10-07',
  'last_update': '2020-10-08 04:23:56',
  'confirmed': 546952,
  'confirmed_diff': 14173,
  'deaths': 42605,
  'deaths_diff': 70,
  'recovered': 2425,
  'recovered_diff': 8,
  'active': 501922,
  'active_diff': 14095,
  'fatality_rate': 0.0779},
 {'date': '2020-10-08',
  'last_update': '2020-10-09 04:23:59',
  'confirmed': 564502,
  'confirmed_diff': 17550,
  'deaths': 42682,
  'deaths_diff': 77,
  'recovered': 2474,
  'recovered_diff': 49,
  'active': 519346,
  'active_diff': 17424,
  'fatality_rate': 0.0756},
 {'date': '2020-10-09',
  'last_update': '2020-10-10 04:23:57',
  'confirmed': 578390,
  'confirmed_diff': 13888,
  'deaths': 42769,
  'deaths_diff': 87,
  'recovered': 2488,
  'recovered_diff': 14,
  'active': 533133,
  'active_diff': 13787,
  'fatality_rate': 0.0739},
 {'date': '2020-10-10',
  'last_update': '2020-10-11 04:23:46',
  'confirmed': 593565,
  'confirmed_diff': 15175,
  'deaths': 42850,
  'deaths_diff': 81,
  'recovered': 2495,
  'recovered_diff': 7,
  'active': 548220,
  'active_diff': 15087,
  'fatality_rate': 0.0722},
 {'date': '2020-10-11',
  'last_update': '2020-10-12 04:23:45',
  'confirmed': 606447,
  'confirmed_diff': 12882,
  'deaths': 42915,
  'deaths_diff': 65,
  'recovered': 2503,
  'recovered_diff': 8,
  'active': 561029,
  'active_diff': 12809,
  'fatality_rate': 0.0708},
 {'date': '2020-10-12',
  'last_update': '2020-10-13 04:24:02',
  'confirmed': 620458,
  'confirmed_diff': 14011,
  'deaths': 42965,
  'deaths_diff': 50,
  'recovered': 2511,
  'recovered_diff': 8,
  'active': 574982,
  'active_diff': 13953,
  'fatality_rate': 0.0692},
 {'date': '2020-10-13',
  'last_update': '2020-10-14 04:24:05',
  'confirmed': 637708,
  'confirmed_diff': 17250,
  'deaths': 43108,
  'deaths_diff': 143,
  'recovered': 2535,
  'recovered_diff': 24,
  'active': 592065,
  'active_diff': 17083,
  'fatality_rate': 0.0676},
 {'date': '2020-10-14',
  'last_update': '2020-10-15 04:24:28',
  'confirmed': 657459,
  'confirmed_diff': 19751,
  'deaths': 43245,
  'deaths_diff': 137,
  'recovered': 2551,
  'recovered_diff': 16,
  'active': 611663,
  'active_diff': 19598,
  'fatality_rate': 0.0658},
 {'date': '2020-10-15',
  'last_update': '2020-10-16 04:24:01',
  'confirmed': 676455,
  'confirmed_diff': 18996,
  'deaths': 43383,
  'deaths_diff': 138,
  'recovered': 2561,
  'recovered_diff': 10,
  'active': 630511,
  'active_diff': 18848,
  'fatality_rate': 0.0641},
 {'date': '2020-10-16',
  'last_update': '2020-10-17 04:24:12',
  'confirmed': 692112,
  'confirmed_diff': 15657,
  'deaths': 43519,
  'deaths_diff': 136,
  'recovered': 2565,
  'recovered_diff': 4,
  'active': 646028,
  'active_diff': 15517,
  'fatality_rate': 0.0629},
 {'date': '2020-10-17',
  'last_update': '2020-10-18 04:24:25',
  'confirmed': 708298,
  'confirmed_diff': 16186,
  'deaths': 43669,
  'deaths_diff': 150,
  'recovered': 2572,
  'recovered_diff': 7,
  'active': 662057,
  'active_diff': 16029,
  'fatality_rate': 0.0617},
 {'date': '2020-10-18',
  'last_update': '2020-10-19 04:24:16',
  'confirmed': 725292,
  'confirmed_diff': 16994,
  'deaths': 43736,
  'deaths_diff': 67,
  'recovered': 2589,
  'recovered_diff': 17,
  'active': 678967,
  'active_diff': 16910,
  'fatality_rate': 0.0603},
 {'date': '2020-10-19',
  'last_update': '2020-10-20 04:24:22',
  'confirmed': 744122,
  'confirmed_diff': 18830,
  'deaths': 43816,
  'deaths_diff': 80,
  'recovered': 2613,
  'recovered_diff': 24,
  'active': 697693,
  'active_diff': 18726,
  'fatality_rate': 0.0589},
 {'date': '2020-10-20',
  'last_update': '2020-10-21 04:24:14',
  'confirmed': 765487,
  'confirmed_diff': 21365,
  'deaths': 44057,
  'deaths_diff': 241,
  'recovered': 2626,
  'recovered_diff': 13,
  'active': 718804,
  'active_diff': 21111,
  'fatality_rate': 0.0576},
 {'date': '2020-10-21',
  'last_update': '2020-10-22 04:24:27',
  'confirmed': 792194,
  'confirmed_diff': 26707,
  'deaths': 44248,
  'deaths_diff': 191,
  'recovered': 2636,
  'recovered_diff': 10,
  'active': 745310,
  'active_diff': 26506,
  'fatality_rate': 0.0559},
 {'date': '2020-10-22',
  'last_update': '2020-10-23 04:24:46',
  'confirmed': 813451,
  'confirmed_diff': 21257,
  'deaths': 44437,
  'deaths_diff': 189,
  'recovered': 2652,
  'recovered_diff': 16,
  'active': 766362,
  'active_diff': 21052,
  'fatality_rate': 0.0546},
 {'date': '2020-10-23',
  'last_update': '2020-10-24 04:24:46',
  'confirmed': 834010,
  'confirmed_diff': 20559,
  'deaths': 44661,
  'deaths_diff': 224,
  'recovered': 2657,
  'recovered_diff': 5,
  'active': 786692,
  'active_diff': 20330,
  'fatality_rate': 0.0535},
 {'date': '2020-10-24',
  'last_update': '2020-10-25 04:24:36',
  'confirmed': 857043,
  'confirmed_diff': 23033,
  'deaths': 44835,
  'deaths_diff': 174,
  'recovered': 2676,
  'recovered_diff': 19,
  'active': 809532,
  'active_diff': 22840,
  'fatality_rate': 0.0523},
 {'date': '2020-10-25',
  'last_update': '2020-10-26 04:25:02',
  'confirmed': 876840,
  'confirmed_diff': 19797,
  'deaths': 44986,
  'deaths_diff': 151,
  'recovered': 2685,
  'recovered_diff': 9,
  'active': 829169,
  'active_diff': 19637,
  'fatality_rate': 0.0513},
 {'date': '2020-10-26',
  'last_update': '2020-10-27 04:24:45',
  'confirmed': 897740,
  'confirmed_diff': 20900,
  'deaths': 45088,
  'deaths_diff': 102,
  'recovered': 2702,
  'recovered_diff': 17,
  'active': 849950,
  'active_diff': 20781,
  'fatality_rate': 0.0502},
 {'date': '2020-10-27',
  'last_update': '2020-10-28 04:24:39',
  'confirmed': 920664,
  'confirmed_diff': 22924,
  'deaths': 45455,
  'deaths_diff': 367,
  'recovered': 2719,
  'recovered_diff': 17,
  'active': 872490,
  'active_diff': 22540,
  'fatality_rate': 0.0494},
 {'date': '2020-10-28',
  'last_update': '2020-10-29 04:24:49',
  'confirmed': 945378,
  'confirmed_diff': 24714,
  'deaths': 45765,
  'deaths_diff': 310,
  'recovered': 2773,
  'recovered_diff': 54,
  'active': 896840,
  'active_diff': 24350,
  'fatality_rate': 0.0484},
 {'date': '2020-10-29',
  'last_update': '2020-10-30 04:24:49',
  'confirmed': 968456,
  'confirmed_diff': 23078,
  'deaths': 46045,
  'deaths_diff': 280,
  'recovered': 2799,
  'recovered_diff': 26,
  'active': 919612,
  'active_diff': 22772,
  'fatality_rate': 0.0475},
 {'date': '2020-10-30',
  'last_update': '2020-10-31 04:24:44',
  'confirmed': 992874,
  'confirmed_diff': 24418,
  'deaths': 46319,
  'deaths_diff': 274,
  'recovered': 2811,
  'recovered_diff': 12,
  'active': 943744,
  'active_diff': 24132,
  'fatality_rate': 0.0467},
 {'date': '2020-10-31',
  'last_update': '2020-11-01 04:36:19',
  'confirmed': 1014793,
  'confirmed_diff': 21919,
  'deaths': 46645,
  'deaths_diff': 326,
  'recovered': 2839,
  'recovered_diff': 28,
  'active': 965309,
  'active_diff': 21565,
  'fatality_rate': 0.046},
 {'date': '2020-11-01',
  'last_update': '2020-11-02 05:25:04',
  'confirmed': 1038054,
  'confirmed_diff': 23261,
  'deaths': 46807,
  'deaths_diff': 162,
  'recovered': 2841,
  'recovered_diff': 2,
  'active': 988406,
  'active_diff': 23097,
  'fatality_rate': 0.0451}]

In [14]:
import pandas as pd
pd.DataFrame(data)

,date,last_update,confirmed,confirmed_diff,deaths,deaths_diff,recovered,recovered_diff,active,active_diff,fatality_rate
0,2020-10-03,2020-10-04 04:23:44,482654,12885,42407,49,2396,7,437851,12829,0.0879
1,2020-10-04,2020-10-05 04:23:33,505619,22965,42440,33,2403,7,460776,22925,0.0839
2,2020-10-05,2020-10-06 04:23:33,518222,12603,42459,19,2409,6,473354,12578,0.0819
3,2020-10-06,2020-10-07 04:23:40,532779,14557,42535,76,2417,8,487827,14473,0.0798
4,2020-10-07,2020-10-08 04:23:56,546952,14173,42605,70,2425,8,501922,14095,0.0779
5,2020-10-08,2020-10-09 04:23:59,564502,17550,42682,77,2474,49,519346,17424,0.0756
6,2020-10-09,2020-10-10 04:23:57,578390,13888,42769,87,2488,14,533133,13787,0.0739
7,2020-10-10,2020-10-11 04:23:46,593565,15175,42850,81,2495,7,548220,15087,0.0722
8,2020-10-11,2020-10-12 04:23:45,606447,12882,42915,65,2503,8,561029,12809,0.0708
9,2020-10-12,2020-10-13 04:24:02,620458,14011,42965,50,2511,8,574982,13953,0.0692
10,2020-10-13,2020-10-14 04:24:05,637708,17250,43108,143,2535,24,592065,17083,0.0676
11,2020-10-14,2020-10-15 04:24:28,657459,19751,43245,137,2551,16,611663,19598,0.0658
12,2020-10-15,2020-10-16 04:24:01,676455,18996,43383,138,2561,10,630511,18848,0.0641
13,2020-10-16,2020-10-17 04:24:12,692112,15657,43519,136,2565,4,646028,15517,0.0629
14,2020-10-17,2020-10-18 04:24:25,708298,16186,43669,150,2572,7,662057,16029,0.0617
15,2020-10-18,2020-10-19 04:24:16,725292,16994,43736,67,2589,17,678967,16910,0.0603
16,2020-10-19,2020-10-20 04:24:22,744122,18830,43816,80,2613,24,697693,18726,0.0589
17,2020-10-20,2020-10-21 04:24:14,765487,21365,44057,241,2626,13,718804,21111,0.0576
18,2020-10-21,2020-10-22 04:24:27,792194,26707,44248,191,2636,10,745310,26506,0.0559
19,2020-10-22,2020-10-23 04:24:46,813451,21257,44437,189,2652,16,766362,21052,0.0546
20,2020-10-23,2020-10-24 04:24:46,834010,20559,44661,224,2657,5,786692,20330,0.0535
21,2020-10-24,2020-10-25 04:24:36,857043,23033,44835,174,2676,19,809532,22840,0.0523
22,2020-10-25,2020-10-26 04:25:02,876840,19797,44986,151,2685,9,829169,19637,0.0513
23,2020-10-26,2020-10-27 04:24:45,897740,20900,45088,102,2702,17,849950,20781,0.0502
24,2020-10-27,2020-10-28 04:24:39,920664,22924,45455,367,2719,17,872490,22540,0.0494
25,2020-10-28,2020-10-29 04:24:49,945378,24714,45765,310,2773,54,896840,24350,0.0484
26,2020-10-29,2020-10-30 04:24:49,968456,23078,46045,280,2799,26,919612,22772,0.0475
27,2020-10-30,2020-10-31 04:24:44,992874,24418,46319,274,2811,12,943744,24132,0.0467
28,2020-10-31,2020-11-01 04:36:19,1014793,21919,46645,326,2839,28,965309,21565,0.0460
29,2020-11-01,2020-11-02 05:25:04,1038054,23261,46807,162,2841,2,988406,23097,0.0451

## API example - Spotify

In [16]:
import requests

CLIENT_ID = "your client id"
CLIENT_SECRET = "your client secret"

AUTH_URL = "https://accounts.spotify.com/api/token"
auth_response = requests.post(AUTH_URL, {
    'grant_type': 'client_credentials',
    'client_id': CLIENT_ID,
    'client_secret': CLIENT_SECRET,
})

#Convert response to JSON
auth_response_data = auth_response.json()

#Save the access token
access_token = auth_response_data['access_token']

#Need to pass access token into header to send properly formed GET request to API server
headers = {
    'Authorization': 'Bearer {token}'.format(token=access_token)
}

In [17]:
BASE_URL = 'https://api.spotify.com/v1/'
r = requests.get(BASE_URL + 'artists/06HL4z0CvFAxyc27GXpf02', headers=headers)
r.json()

{'external_urls': {'spotify': 'https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02'},
 'followers': {'href': None, 'total': 136163541},
 'genres': [],
 'href': 'https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02',
 'id': '06HL4z0CvFAxyc27GXpf02',
 'images': [{'url': 'https://i.scdn.co/image/ab6761610000e5ebe672b5f553298dcdccb0e676',
   'height': 640,
   'width': 640},
  {'url': 'https://i.scdn.co/image/ab67616100005174e672b5f553298dcdccb0e676',
   'height': 320,
   'width': 320},
  {'url': 'https://i.scdn.co/image/ab6761610000f178e672b5f553298dcdccb0e676',
   'height': 160,
   'width': 160}],
 'name': 'Taylor Swift',
 'popularity': 98,
 'type': 'artist',
 'uri': 'spotify:artist:06HL4z0CvFAxyc27GXpf02'}