<a href="https://colab.research.google.com/github/Liping-LZ/BDAO_DSDO_2425/blob/main/Big_data_analytics/IMA_support/BDAO_IMA_Cloud_Project_Demo_Code_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Authentication**

Everytime before you make connection to Google Cloud via API, you need to run the below code to grant access to Google Cloud services.

In [1]:
# Authenticate and access Google Cloud services
from google.colab import auth
auth.authenticate_user()

# **Tell under which Google Cloud project you are working**

Replace the "your project id" with your actual project id. Visit https://console.cloud.google.com/ and copy your project id by clicking into the project window on top left.

In [2]:
project_id = "your project id"

### (Optional) Create a new project in Google Cloud

Of course, you can continue using the existed project if you wish. But if you want an independent project to handle the data and analysis, you can create a new project in your Google Cloud. After you create the project, copy the id to the above code cell.
![picture](https://drive.google.com/uc?id=18bayQbOjHw8Uq-QkMwYhupi8FPtT9Dmm)

# **Option 1: Download data from Google Cloud Storage directly**

- Business data – gs://yelp-data-ima/yelp_academic_dataset_business_processed.json
- Check-in data – gs://yelp-data-ima/yelp_academic_dataset_checkin.json
- User data – gs://yelp-data-ima/yelp_academic_dataset_user.json
- Tips data – gs://yelp-data-ima/yelp_academic_dataset_tip.json
- Review data - gs://yelp-data-ima/yelp_academic_dataset_review.json

The following codes show you and example of downloading data from Google Cloud Storage using the provided uri. The uri follows the patter: gs://bucket_name/blob_name. You can replace the blob name (with data you would like to download) in the following codes to download respective dataset.

In [ ]:
# In this example, we download the business dataset from GCS

from google.cloud import storage
import pandas as pd
from io import StringIO

# Replace with your actual bucket and blob names
bucket_name = "yelp-data-ima"
blob_name = "yelp_academic_dataset_review.json"

# Initialize a Google Cloud Storage client
storage_client = storage.Client()

# Get the bucket and blob
bucket = storage_client.bucket(bucket_name)
blob = bucket.blob(blob_name)

# Download the blob's content as a string
data = blob.download_as_string()

# Decode the JSON data and read it into a pandas DataFrame
df = pd.read_json(StringIO(data.decode('utf-8')), orient='record', lines=True)

# Now you can work with the DataFrame 'df'
df.head()

# **Option 2: Load data into BigQuery**

Instead, you can load data into data warehouse for easy data query. The following codes help you load data from bucket to your BigQuery.

### Step 1: Create a new dataset in your BigQuery to store your project data

In [ ]:
# Import the necessary libraries
from google.cloud import storage
from google.cloud import bigquery

In [ ]:
# Create a dataset in GBQ to load tables
def create_dataset(project_id, dataset_id, location="US"):
    client = bigquery.Client(project=project_id)
    dataset_ref = bigquery.DatasetReference(project_id, dataset_id)
    dataset = bigquery.Dataset(dataset_ref)
    dataset.location = location

    created_dataset = client.create_dataset(dataset, timeout=30)  # Waits 30 seconds
    print("Dataset {} created.".format(created_dataset.dataset_id))

# Replace 'your-new-datatset-name' with your desired dataset name
create_dataset(project_id, 'your-new-datatset-name')

Dataset restaurant_dataset created.

### Step 2: Load data into the dataset you just created in BigQuery

We will load the data one by one in GBQ as tables. Of course, it is possible we load all the data at once by writing a for loop, but here we just simplify the code and it would be easier for us to identify issues if there are any.

You could also choose to load part of the dataset into BigQuery following your need.

#### 01 Load business dataset into GBQ

In [ ]:
dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
table_name = "your-table-name" # Replace 'your-table-name' with your desired table name
bucket_name = "yelp-data-ima" # don't make changes here
blob_name = "yelp_academic_dataset_business_processed.json" # don't make changes here

bigquery_client = bigquery.Client(project=project_id)

dataset_ref = bigquery_client.dataset(dataset_name)
table_ref = dataset_ref.table(table_name)

job_config = bigquery.LoadJobConfig()
job_config.autodetect = True
job_config.source_format = bigquery.SourceFormat.NEWLINE_DELIMITED_JSON

load_job = bigquery_client.load_table_from_uri(
    f"gs://{bucket_name}/{blob_name}",
    table_ref,
    job_config=job_config
)

load_job.result()

print(f"Data loaded into BigQuery: {project_id}.{dataset_name}.{table_name}")

Data loaded into BigQuery: big-synthesizer-421522.restaurant_dataset.restaurant_data

#### 02 Load tips dataset into GBQ

In [ ]:
dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
table_name = "your-table-name" # Replace 'your-table-name' with your desired table name
bucket_name = "yelp-data-ima" # don't make changes here
blob_name = "yelp_academic_dataset_tip.json" # don't make changes here

bigquery_client = bigquery.Client(project=project_id)

dataset_ref = bigquery_client.dataset(dataset_name)
table_ref = dataset_ref.table(table_name)

job_config = bigquery.LoadJobConfig()
job_config.autodetect = True
job_config.source_format = bigquery.SourceFormat.NEWLINE_DELIMITED_JSON

load_job = bigquery_client.load_table_from_uri(
    f"gs://{bucket_name}/{blob_name}",
    table_ref,
    job_config=job_config
)

load_job.result()

print(f"Data loaded into BigQuery: {project_id}.{dataset_name}.{table_name}")

Data loaded into BigQuery: big-synthesizer-421522.restaurant_dataset.restaurant_data

#### 03 Load check-in dataset into GBQ

In [ ]:
dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
table_name = "your-table-name" # Replace 'your-table-name' with your desired table name
bucket_name = "yelp-data-ima" # don't make changes here
blob_name = "yelp_academic_dataset_checkin.json" # don't make changes here

bigquery_client = bigquery.Client(project=project_id)

dataset_ref = bigquery_client.dataset(dataset_name)
table_ref = dataset_ref.table(table_name)

job_config = bigquery.LoadJobConfig()
job_config.autodetect = True
job_config.source_format = bigquery.SourceFormat.NEWLINE_DELIMITED_JSON

load_job = bigquery_client.load_table_from_uri(
    f"gs://{bucket_name}/{blob_name}",
    table_ref,
    job_config=job_config
)

load_job.result()

print(f"Data loaded into BigQuery: {project_id}.{dataset_name}.{table_name}")

Data loaded into BigQuery: big-synthesizer-421522.restaurant_dataset.restaurant_data

#### 04 Load review dataset into GBQ

In [ ]:
dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
table_name = "your-table-name" # Replace 'your-table-name' with your desired table name
bucket_name = "yelp-data-ima" # don't make changes here
blob_name = "yelp_academic_dataset_review.json" # don't make changes here

bigquery_client = bigquery.Client(project=project_id)

dataset_ref = bigquery_client.dataset(dataset_name)
table_ref = dataset_ref.table(table_name)

job_config = bigquery.LoadJobConfig()
job_config.autodetect = True
job_config.source_format = bigquery.SourceFormat.NEWLINE_DELIMITED_JSON

load_job = bigquery_client.load_table_from_uri(
    f"gs://{bucket_name}/{blob_name}",
    table_ref,
    job_config=job_config
)

load_job.result()

print(f"Data loaded into BigQuery: {project_id}.{dataset_name}.{table_name}")

Data loaded into BigQuery: big-synthesizer-421522.restaurant_dataset.restaurant_data

#### 05 Load user dataset into GBQ

In [ ]:
dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
table_name = "your-table-name" # Replace 'your-table-name' with your desired table name
bucket_name = "yelp-data-ima" # don't make changes here
blob_name = "yelp_academic_dataset_user.json" # don't make changes here

bigquery_client = bigquery.Client(project=project_id)

dataset_ref = bigquery_client.dataset(dataset_name)
table_ref = dataset_ref.table(table_name)

job_config = bigquery.LoadJobConfig()
job_config.autodetect = True
job_config.source_format = bigquery.SourceFormat.NEWLINE_DELIMITED_JSON

load_job = bigquery_client.load_table_from_uri(
    f"gs://{bucket_name}/{blob_name}",
    table_ref,
    job_config=job_config
)

load_job.result()

print(f"Data loaded into BigQuery: {project_id}.{dataset_name}.{table_name}")

Data loaded into BigQuery: big-synthesizer-421522.restaurant_dataset.restaurant_data

Until here, you have successfully loaded all data into your data warehouse (BigQuery) in Google Cloud.

# **Query data from BigQuery and do analysis**

Now that the data is stored in BigQuery, you can make connection to BigQuery and extract data you want.

### Query data from business dataset (examples)

In [ ]:
# First make connection to the table in GBQ
from google.cloud import storage
from google.cloud import bigquery

dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
table_name = "your-table-name" # Replace 'your-table-name' with the table name you want to make connection with

bigquery_client = bigquery.Client(project=project_id)

In [ ]:
# Query all data from the table
query = f"""
    SELECT *
    FROM `{project_id}.{dataset_name}.{table_name}`
"""

query_job = bigquery_client.query(query)
results = query_job.result()

restaurant_df = query_job.to_dataframe()
restaurant_df.head()

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,NoiseLevel,GoodForMeal,BusinessAcceptsBitcoin,Smoking,Music,GoodForDancing,BestNights,BYOB,Corkage,Parking
0,kfNv-JZpuN6TVNSO6hHdkw,Hibachi Express,6625 E 82nd St,Indianapolis,IN,46250,39.904320,-86.053080,4.0,20,...,None,None,<NA>,None,None,<NA>,None,<NA>,<NA>,<NA>
1,sqSqqLy0sN8n2IZrAbzidQ,Domino's Pizza,3001 Highway 31 W,White House,TN,37188,36.464747,-86.659187,3.5,8,...,None,None,<NA>,None,None,<NA>,None,<NA>,<NA>,<NA>
2,ABxoFuzZy5mqQ8C5FJJajQ,Core de Roma,201 Jefferson St,Bala Cynwyd,PA,19004,40.028357,-75.238084,5.0,12,...,None,None,<NA>,None,None,<NA>,None,<NA>,<NA>,True
3,RK6-cJ9hj53RzOlCBmpT-g,Impasto,None,Tampa,FL,33611,27.890814,-82.502346,5.0,5,...,None,None,<NA>,None,None,<NA>,None,<NA>,<NA>,<NA>
4,EuRGgOwJ0g1vTj2R04j37Q,Crafty Crab,51 Ludwig Dr,Fairview Heights,IL,62208,38.601298,-89.989683,2.5,14,...,None,None,<NA>,None,None,<NA>,None,<NA>,<NA>,True

In [ ]:
# Query data from selected columns from the table
query = f"""
    SELECT business_id, name, address, city, state, stars, review_count, is_open, categories
    FROM `{project_id}.{dataset_name}.{table_name}`
"""

query_job = bigquery_client.query(query)
results = query_job.result()

restaurant_df = query_job.to_dataframe()
restaurant_df.head()

,business_id,name,address,city,state,stars,review_count,is_open,categories
0,bw90rjFL02A_8rVE34m5Lg,Cosmetic Solutions,1010 Lula Lula Dr,Lula Lula,HI,3.5,17,1,"Cosmetic Surgeons, Pizza, Doctors, Beauty & Sp..."
1,em474WuTw7-OkhPfX4EohA,IHOP,702 Blowing Rock Rd,Boone,NC,2.0,29,0,"Breakfast & Brunch, Coffee & Tea, Food, Americ..."
2,gCF0QQWzI9lDouhLfTbYCA,MudMan Food Truck,None,Kalispell,MT,5.0,6,0,"Restaurants, American (Traditional), Food Truc..."
3,1H9WYGFJ4AFwXq7WCOOMtg,Two Elk Restaurant,12000 Skyline Dr,Vail,CO,3.5,12,0,"Buffets, Restaurants"
4,IvQs2hhXKZ4NgZhVZ5jjjQ,Pumpernickles Catering,95a Mount Pleasant,Liverpool,XMS,4.0,5,1,"Caterers, Breakfast & Brunch, Convenience Stor..."

In [ ]:
# Query data based on condition from the table
query = f"""
    SELECT *
    FROM `{project_id}.{dataset_name}.{table_name}`
    WHERE state = 'PA'
"""

query_job = bigquery_client.query(query)
results = query_job.result()

restaurant_df = query_job.to_dataframe()
restaurant_df.head()

### Query data from check-in dataset (examples)

In [ ]:
# First make connection to the table in GBQ
from google.cloud import storage
from google.cloud import bigquery

dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
table_name = "your-table-name" # Replace 'your-table-name' with the table name you want to make connection with

bigquery_client = bigquery.Client(project=project_id)

In [ ]:
# Query all data from the table
query = f"""
    SELECT *
    FROM `{project_id}.{dataset_name}.{table_name}`
"""

query_job = bigquery_client.query(query)
results = query_job.result()

checkin_df = query_job.to_dataframe()
checkin_df.head()

In [ ]:
# Query data based on condition from the table
query = f"""
    SELECT *
    FROM `{project_id}.{dataset_name}.{table_name}`
    WHERE year >=2020
"""

query_job = bigquery_client.query(query)
results = query_job.result()

restaurant_df = query_job.to_dataframe()
restaurant_df.head()

### Query data from tips dataset file (examples)

In [ ]:
# First make connection to the table in GBQ
from google.cloud import storage
from google.cloud import bigquery

dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
table_name = "your-table-name" # Replace 'your-table-name' with the table name you want to make connection with

bigquery_client = bigquery.Client(project=project_id)

In [ ]:
# Query all data from the table
query = f"""
    SELECT *
    FROM `{project_id}.{dataset_name}.{table_name}`
"""

query_job = bigquery_client.query(query)
results = query_job.result()

checkin_df = query_job.to_dataframe()
checkin_df.head()

In [ ]:
# Query data from selected columns from the table
query = f"""
    SELECT user_id, business_id, text,date
    FROM `{project_id}.{dataset_name}.{table_name}`
"""

query_job = bigquery_client.query(query)
results = query_job.result()

checkin_df = query_job.to_dataframe()
checkin_df.head()

### Query data from review dataset file (examples)

In [ ]:
# First make connection to the table in GBQ
from google.cloud import storage
from google.cloud import bigquery

dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
table_name = "your-table-name" # Replace 'your-table-name' with the table name you want to make connection with

bigquery_client = bigquery.Client(project=project_id)

In [ ]:
# Query all data from the table
query = f"""
    SELECT *
    FROM `{project_id}.{dataset_name}.{table_name}`
"""

query_job = bigquery_client.query(query)
results = query_job.result()

checkin_df = query_job.to_dataframe()
checkin_df.head()

In [ ]:
# Query data from selected columns from the table
query = f"""
    SELECT review_id, user_id, business_id, date, star, text, useful
    FROM `{project_id}.{dataset_name}.{table_name}`
"""

query_job = bigquery_client.query(query)
results = query_job.result()

checkin_df = query_job.to_dataframe()
checkin_df.head()

In [ ]:
# Query data based on condition from the table
query = f"""
    SELECT review_id, user_id, business_id, date, star, text, useful
    FROM `{project_id}.{dataset_name}.{table_name}`
    WHERE star>=4
"""

query_job = bigquery_client.query(query)
results = query_job.result()

checkin_df = query_job.to_dataframe()
checkin_df.head()

### Query data from user dataset file (examples)

In [ ]:
# First make connection to the table in GBQ
from google.cloud import storage
from google.cloud import bigquery

dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
table_name = "your-table-name" # Replace 'your-table-name' with the table name you want to make connection with

bigquery_client = bigquery.Client(project=project_id)

In [ ]:
# Query all data from the table
query = f"""
    SELECT *
    FROM `{project_id}.{dataset_name}.{table_name}`
"""

query_job = bigquery_client.query(query)
results = query_job.result()

checkin_df = query_job.to_dataframe()
checkin_df.head()

In [ ]:
# Query data from selected columns from the table
query = f"""
    SELECT user_id, review_count, yelping_since, fans, average_stars
    FROM `{project_id}.{dataset_name}.{table_name}`
"""

query_job = bigquery_client.query(query)
results = query_job.result()

checkin_df = query_job.to_dataframe()
checkin_df.head()

### Joining tables through SQL query (example)

In [ ]:
# First make connection to the table in GBQ
from google.cloud import storage
from google.cloud import bigquery

dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
table_1 = "your-table-name" # Replace 'your-table-name' with the name of the table you want to join
table_2 = "your-table-name" # Replace 'your-table-name' with the name of the table you want to join

bigquery_client = bigquery.Client(project=project_id)

You need to check the ERD (entity relationship diagram) before merging data. Business dataset, tips dataset, check-in dataset and review dataset can be joined by business_id. However, tips dataset and review dataset all have multiple entries for one business, which means you need to map the business information from business dataset to tips or review dataset if you want the merge. Review data and user data can be connected by user_id. You can map the user information to review dataset if you want.

In [ ]:
# Below is the example to merge business dataset and check-in dataset
query = f"""
    SELECT r.business_id, r.name, r.address, r.city, r.state, r.stars, r.review_count, r.is_open, r.categories,c.business_id, c.date
    FROM `{project_id}.{dataset_name}.{table_2}` AS c
    JOIN `{project_id}.{dataset_name}.{table_1}` AS r on r.business_id = c.business_id
    WHERE r.review_count>1000
"""

query_job = bigquery_client.query(query)
results = query_job.result()

join_df = query_job.to_dataframe()
join_df.head()

If you are not familiar with SQL, you can just query the dataset and then use Python to merge or join them if you need.

# **Data processing and data analysis**

Since the query data is converted into dataframe, you can easily use Python to do analysis or modelling. This is up to you how you would do.

# **Store the transformed data back to BigQuery for visualisation**

We know data visualisation requires clean data and if we read data directly in Tableau it might crash because the data size is large and the data might messy.

You could consider using Python to clean and process your data and then you can store the transformed data table back to BigQuery and then you can make connections to the transformed table in Tableau to do visualisation.

In [ ]:
# Make sure pandas-gbq is installed
# !pip install pandas-gbq

dataset_name = "your-dataset-name" # Replace 'your-dataset-name' with the dataset name you created
transformed_table_name = "your-transformed-table-name" # Replace 'your-transformed-table-name' with the new table name you desire
destination_table = f'{dataset_name}.{transformed_table_name}'

# Use the to_gbq function to upload the DataFrame (after data processing) to BigQuery
df.to_gbq(destination_table, project_id=project_id, if_exists='replace', progress_bar=True) # here we assume your transformed data is named "df"

100%|██████████| 1/1 [00:00<00:00, 1563.29it/s]

By running the above code, you should be able to see there is a new table uploaded to BigQuery under your dataset.

Next, you can consider using Tableau for some visual analysis:)

Let me know if you have further questions.